version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    volumes:
      - 'esdata:/elasticsearch_data'
    ports:
      - '9200:9200'

  kibana:
    image: moorecodes/ezops_kibana:latest
    # volumes:
    #   - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    depends_on:
      - es

volumes:
  esdata:
