version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    volumes:
      - 'esdata:/elasticsearch_data'
    ports:
      - '9200:9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    depends_on:
      - es

volumes:
  esdata:
